name: real_social_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4
  auto_route: ^10.0.1
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.3.0
  flex_color_scheme: ^8.1.1
  shared_preferences: ^2.5.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
